#!/usr/bin/env python
import math
import sys

vat_rate = 0.19
income_tax_rate = 0.4

##price = 30 + 30 + 135 + 90 + 148 + 50 + 129 + 270 + 326 + 704 + 21 + 37 + 62 + 85 + 139 + 2346 
price = float(sys.argv[1])

price_net = price * (1.0 - vat_rate)
price_after_income_tax = price_net * (1.0 - income_tax_rate)

years = 18

alt_money = price * (1.08 ** years)
alt_vat = (price - price_net) * (1.08 ** years)
alt_ret = (price - price_after_income_tax) * (1.08 ** years)

print("Gross price:      {:8.2f}".format(price))
print("Net price:        {:8.2f}".format(price_net))
print("Aft. tax price:   {:8.2f}".format(price_after_income_tax))
print("-----------------------------------")
print("Vat return:       {:8.2f}".format(price - price_net))
print("Tax return:       {:8.2f}".format(price_net * income_tax_rate))
print("Total return:     {:8.2f}".format(price - price_after_income_tax))
print("-----------------------------------")
print("alt {}y:          {:8.2f}".format(years, alt_money))
print("vat {}y:          {:8.2f}".format(years, alt_vat))
print("ret {}y:          {:8.2f}".format(years, alt_ret))

