#!/usr/bin/python3.7
# EASY-INSTALL-ENTRY-SCRIPT: 'shreddit==6.0.7','console_scripts','shreddit'
__requires__ = 'shreddit==6.0.7'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('shreddit==6.0.7', 'console_scripts', 'shreddit')()
    )
