#!/usr/bin/env python
import soco
import sys
import urllib
import os

def get_zone(name):
    return soco.SoCo("192.168.0.88")
    #return soco.discovery.by_name(name)

def is_playing(zone):
    return zone.get_current_transport_info()["current_transport_state"] == "PLAYING"

def p_track(zone, nopref=False):
    prefix = ""
    if is_playing(zone):
        prefix = "🎵 "
    else:
        prefix = "💤 "
    if nopref:
        prefix = ""
    artist = zone.get_current_track_info()["artist"]
    title = zone.get_current_track_info()["title"]
    s = prefix + artist + " - " + title
    print(s)

def p_track_poly(zone):
   vol = zone.volume
   if is_playing(zone):
       artist = zone.get_current_track_info()["artist"]
       title = zone.get_current_track_info()["title"]
       s = "> " + artist + " - " + title + " | " + " " + str(vol) + "%"
       print(s)
   else:
        print("SONOS |  " + str(vol) + "%")

def p_trackinfo(zone):
    print(zone.get_current_track_info())

def p_transport(zone):
    print(zone.get_current_transport_info())

def p_file(zone):
    fn = zone.get_current_track_info()["uri"]
    fn2 = urllib.parse.urlparse(fn).path
    fn3 = urllib.parse.unquote(fn2)
    fn4 = os.path.basename(fn3)
    print(fn4)

def p_path(zone):
    fn = zone.get_current_track_info()["uri"]
    fn2 = urllib.parse.urlparse(fn).path
    fn3 = urllib.parse.unquote(fn2)
    print(fn3)


z = get_zone("Bedroom")
if z is None:
    print("No Speaker found!")
    exit()

if len(sys.argv) == 1:
    p_track(z)
    exit()

if sys.argv[1] == 'n':
    if not is_playing(z):
        z.play()
    z.next()
    p_track(z, nopref=True)
    exit()

if sys.argv[1] == 'p':
    if is_playing(z):
        z.pause()
    else:
        z.play()

if sys.argv[1] == 't':
    p_transport(z)
    exit()

if sys.argv[1] == 'i':
    p_trackinfo(z)
    exit()

if sys.argv[1] == 'f':
    p_file(z)
    exit()

if sys.argv[1] == 'path':
    p_path(z)
    exit()


if sys.argv[1] == 'poly':
    p_track_poly(z)
    exit()


