#!/bin/sh
homedir=~
eval homedir=$homedir
date=`date +%Y-%m-%d-%H:%M:%S`
fn="${homedir}/Pictures/screenshots/${date}_screenshot.png"
notify-send "Screenshot mode"
import -border $fn
#scrot -bs $fn
notify-send "Screenshot saved to ${fn}"
echo $fn
