#!/bin/bash
youtube-dl -o "%(title)s.%(ext)s" --postprocessor-args '-threads 0' --restrict-filenames -i --extract-audio --audio-format mp3 --audio-quality 3 --embed-thumbnail --metadata-from-title "%(artist)s - %(title)s" --add-metadata "$1"
